# Generated by Django 4.2.4 on 2023-11-30 13:58

import Aplications.descuentos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descuento_porcentaje', models.IntegerField(blank=True, null=True, validators=[Aplications.descuentos.models.validate_two_digit], verbose_name='Porcentaje de descuento')),
                ('descuento_valor', models.IntegerField(blank=True, null=True, verbose_name='Valor de descuento')),
                ('compartido', models.BooleanField(default=True, verbose_name='¿Es compartido?')),
                ('usuarios_asociados', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['fecha'],
            },
        ),
    ]
