# Generated by Django 4.2.4 on 2023-10-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_detail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='detail_image',
        ),
    ]
