# Generated by Django 4.2.4 on 2023-10-14 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0005_producto_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total a pagar')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio_de_pago', models.CharField(choices=[('0', 'Mercado Pago'), ('1', 'Tarjeta de crédito'), ('2', 'Tarjeta de débito')], max_length=1, verbose_name='Medio de Pago')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['fecha'],
            },
        ),
    ]
