# Generated by Django 4.2.4 on 2023-11-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
